services:
  - type: web
    name: pollution-free-routing
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
